jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      id: gradle-cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: '~/.gradle/caches

          '
    - continue-on-error: true
      id: gradle-wrapper-cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
        path: '~/.gradle/wrapper

          '
    - continue-on-error: true
      name: Build
      run: ./gradlew build
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
  validation:
    name: Gradle Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1
name: PR Build
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
